=== dtpthao/Java-Core/training/Practice7/msc/namespace/Bank-with-no-targetNamespace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<!--============================================================
This XML schema contains no targetNamespace.
ALL declared names belong to NO NAMESPACE.
=============================================================-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Bank">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Deposit" 
					type="tns:Deposit" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="Deposit">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="Country" type="xsd:token"/>
			<xsd:element name="Depositor" type="xsd:string"/>
			<xsd:element name="AccountID" type="xsd:ID" />
			<xsd:element name="Type" type="tns:Type" />
			<xsd:element name="AmountOnDeposit" type="xsd:decimal" />
			<xsd:element name="Profitability" type="xsd:decimal" />
			<xsd:element name="TimeConstraints" type="xsd:duration" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="Type" final="restriction">
		<xsd:restriction base="xsd:string">
    			<xsd:enumeration value="Demand"/>
    			<xsd:enumeration value="Fixed"/>
    			<xsd:enumeration value="Term"/>
    			<xsd:enumeration value="Saving"/>
    			<xsd:enumeration value="Accumulative"/>
    			<xsd:enumeration value="Metal"/>
  		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== dtpthao/Java-Core/training/Practice7/msc/namespace/Bank-with-no-targetNamespace.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test-with-no-targetNamespace.xsd -->

<!--============================================================
When we use xsi:noNamespaceSchemaLocation in XML 
we directly determine that XSD has NO target namespace.
ALL declared in XSD names we used in XML belong to NO NAMESPACE.
=============================================================-->
<Bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="Bank-with-no-targetNamespace.xsd">		
	<Deposit>
		<Name>BlockChain</Name>
		<Country></Country>
		<Depositor>Thao</Depositor>
		<AccountID>ID-3</AccountID>
		<Type>Demand</Type>
		<AmountOnDeposit>3333333</AmountOnDeposit>
		<Profitability>0.15</Profitability>
		<TimeConstraints>P2Y</TimeConstraints>
	</Deposit>
	
	<Deposit>
		<Name>Privat</Name>
		<Country>Ukraina</Country>
		<Depositor>Someone</Depositor>
		<AccountID>ID-1</AccountID>
		<Type>Saving</Type>
		<AmountOnDeposit>0293410</AmountOnDeposit>
		<Profitability>0</Profitability>
		<TimeConstraints>P1Y</TimeConstraints>
	</Deposit>

	<Deposit>
		<Name>Paypal</Name>
		<Country>Ukraine</Country>
		<Depositor>SomeoneElse</Depositor>
		<AccountID>ID-2</AccountID>
		<Type>Term</Type>
		<AmountOnDeposit>2937983</AmountOnDeposit>
		<Profitability>0.1</Profitability>
		<TimeConstraints>P2Y</TimeConstraints>
	</Deposit>			
</Bank>
